CREATE TABLE IF NOT EXISTS "flowers" (
	"id_flower" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name_flower" VARCHAR(32) NOT NULL,
	"image_flower" VARCHAR(255),
	"price_flower" DECIMAL NOT NULL,
	"stock_flower" INTEGER,
	PRIMARY KEY("id_flower")
);




CREATE TABLE IF NOT EXISTS "user_credentials" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username_user" VARCHAR(63) NOT NULL,
	"pass_user" VARCHAR(15) NOT NULL,
	"id_data_users" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "data_users" (
	"id_data_users" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"names_user" VARCHAR(63) NOT NULL,
	"ap_pat_user" VARCHAR(63) NOT NULL,
	"ap_mat_user" VARCHAR(63) NOT NULL,
	"phone_number_user" VARCHAR(10),
	"id_location_users" INTEGER NOT NULL,
	PRIMARY KEY("id_data_users")
);




CREATE TABLE IF NOT EXISTS "location_users" (
	"id_location_users" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"street_user" VARCHAR(15) NOT NULL,
	"num_street_user" INTEGER NOT NULL,
	"num_inter_steet_user" INTEGER,
	PRIMARY KEY("id_location_users")
);



ALTER TABLE "user_credentials"
ADD FOREIGN KEY("id_data_users") REFERENCES "data_users"("id_data_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "location_users"
ADD FOREIGN KEY("id_location_users") REFERENCES "data_users"("id_location_users")
ON UPDATE NO ACTION ON DELETE NO ACTION;